name: Monitor and build, package OpenCC

on:
  schedule:
    # 每月的 2 日 UTC 时间凌晨 1:37 触发
    - cron: '37 1 2 * *'
    # 每月的 17 日 UTC 时间下午 2:15 触发
    - cron: '15 14 17 * *'
  workflow_dispatch:
    inputs:
      version_type:
        description: "Select whether to build the latest release or latest code."
        required: true
        default: "release"
        options:
          - release
          - latest

jobs:
  check_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.version_type == 'release' || github.event_name == 'schedule' }}
    outputs:
      latest_release: ${{ steps.fetch_release.outputs.latest_release }}
    steps:
    - name: Fetch OpenCC Releases
      id: fetch_release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/BYVoid/OpenCC/releases/latest | jq -r .tag_name)
        echo "latest_release=$latest_release" >> $GITHUB_OUTPUT

  download-and-build:
    needs: check_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]

    steps:
    - name: Map OS Names
      id: map_os
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          echo "os_short=linux" >> $GITHUB_ENV
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then
          echo "os_short=windows" >> $GITHUB_ENV
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          echo "os_short=macos" >> $GITHUB_ENV
        fi

    - name: Clone OpenCC repository
      shell: bash
      run: |
        # 判断用户选择逻辑
        if [ "${{ github.event.inputs.version_type }}" == "release" ] && [ -n "${{ needs.check-release.outputs.latest_release }}" ]; then
          echo "Cloning the latest release: ${{ needs.check-release.outputs.latest_release }}"
          git clone --branch ${{ needs.check-release.outputs.latest_release }} https://github.com/BYVoid/OpenCC.git opencc
        else
          echo "Cloning the latest code from the default branch."
          git clone https://github.com/BYVoid/OpenCC.git opencc
        fi

    - name: Build, Install and Package
      working-directory: ./opencc
      shell: bash
      run: |
        cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_INSTALL_PREFIX=install
        cmake --build build --config ${{ matrix.build_type }}
        cmake --install build --prefix build/install
        cpack --config build/CPackConfig.cmake -G ZIP

    - name: Upload Artifact
      uses: actions/upload-artifact@v6
      with:
        name: opencc-${{ env.os_short }}-${{ matrix.build_type }}
        path: opencc/*.zip

    - name: Create a Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0
        files: opencc/*.zip
