name: Monitor and Build OpenCC

on:
  schedule:
    - cron: '0 0 * * *' # 每日 UTC 时间凌晨 0 点触发。
  workflow_dispatch:
    inputs:
      version_type:
        description: "Select whether to build the latest release or latest code."
        required: true
        default: "release"
        options:
          - release
          - latest

jobs:
  check-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.version_type == 'release' }}
    outputs:
      latest_release: ${{ steps.fetch_release.outputs.latest_release }}
    steps:
    - name: Fetch OpenCC Releases
      id: fetch_release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/BYVoid/OpenCC/releases/latest | jq -r .tag_name)
        echo "latest_release=$latest_release" >> $GITHUB_OUTPUT

  download-and-build:
    needs: check-release
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clone OpenCC Code
      shell: bash
      run: |
        # 判断用户选择逻辑
        if [ "${{ github.event.inputs.version_type }}" == "release" ] && [ -n "${{ needs.check-release.outputs.latest_release }}" ]; then
          echo "Cloning the latest release: ${{ needs.check-release.outputs.latest_release }}"
          git clone --branch ${{ needs.check-release.outputs.latest_release }} https://github.com/BYVoid/OpenCC.git opencc
        else
          echo "Cloning the latest code from the default branch."
          git clone https://github.com/BYVoid/OpenCC.git opencc
        fi

    - name: Configure build
      working-directory: ./opencc
      run: cmake -S. -Bbuild -DCMAKE_INSTALL_PREFIX=.

    - name: Build and Install
      working-directory: ./opencc
      run: cmake --build build --config Release --target install

    - name: Archive build artifacts
      uses: actions/upload-artifact@v6
      with:
        name: opencc-windows-binaries
        path: opencc/build

    - name: Create a Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: opencc/build/**
